### ISSUE TITLE
Getting release stable and running

### ISSUE THREAD

**Issue by Krakert** [Krakert/Crypto-Tracker#20]
It looks like making a stable app in release takes some more testing.

**Comment by Krakert** [comment]
The keystore has been reset with the help with Google. Over 2 days (23 Nov) we are able to upload new signed bundles with this new keystore

**Comment by Krakert** [comment]
It looks like we still have a problem in the app:

**Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
       - at java.util.ArrayList.get(ArrayList.java:437)
       - at com.krakert.tracker.ui.AddCoinComposeKt$ShowList$1$1$1.invoke(AddCoinCompose.kt:110)
       - at com.krakert.tracker.ui.AddCoinComposeKt$ShowList$1$1$1.invoke(AddCoinCompose.kt:107)**
